version: "3.8"

volumes:
  appointment_db:

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=appointment
      - POSTGRES_PASSWORD=appointment
      - POSTGRES_DB=appointment
    volumes:
      - appointment_db:/var/lib/postgresql/data/
  web:
    build: .
    restart: always
    command: bash -c "python manage.py migrate 
      && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db