# Generated by Django 5.1.1 on 2024-09-21 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number is not correct!', regex='^09[0-9]{9}$')]),
        ),
    ]
