# Generated by Django 5.1.1 on 2024-09-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_doctorprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.PositiveIntegerField(default=5, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='visit_fee',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Consultation Fee'),
        ),
    ]
