# Generated by Django 5.1.1 on 2024-09-14 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_delete_doctormodel'),
        ('user', '0003_alter_doctorprofile_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_year', models.PositiveIntegerField()),
                ('visit_fee', models.PositiveIntegerField()),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
