# Generated by Django 5.1.1 on 2024-09-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorModel',
        ),
    ]
